spring:
  application:
    name: commerce-ingestion-api
  profiles:
    default: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  h2:
    console:
      enabled: false

server:
  port: 9080

logging:
  level:
    com.logistics: INFO
    org.hibernate.SQL: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
